/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mongo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/mongo.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-110.896, -56.325, -51.595]} rotation={[1.739, 0.008, 0.123]} scale={4.257}>
        <mesh geometry={nodes.back.geometry} material={materials['back.003']} position={[-1.487, 3.883, -1.128]} rotation={[-0.193, -0.006, -1.021]} />
        <mesh geometry={nodes.LOGO.geometry} material={materials['logo.004']} position={[-0.948, 4.375, -1.204]} rotation={[-0.193, -0.006, -1.021]} />
        <mesh geometry={nodes.LOGO_1.geometry} material={materials['logo_1.002']} position={[-0.241, 3.051, -0.324]} rotation={[-0.193, -0.006, -1.021]} />
      </group>
    </group>
  )
}

useGLTF.preload('/mongo.glb')
