/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 css-3d.glb --draco 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function CSS(props) {
  const { nodes, materials } = useGLTF('/public/css-3d.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-4,0,0]} rotation={[0, 130,0]} scale={0.1}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.005']} position={[-142.941, -32.748, -5922.869]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
        <group position={[100,10,-5]}>
          <mesh geometry={nodes.Mesh001.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.Mesh001_1.geometry} material={materials['Material.003']} />
        </group>
        <mesh geometry={nodes.ramka2.geometry} material={materials['Material.001']} position={[-182.684, 35.487, 1926.616]} />
      </group>
    </group>
  )
}

useGLTF.preload('/public/css-3d.glb')
