/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MongoDB.glb --draco 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, Center } from "@react-three/drei";
import gsap from "gsap";

const MongoDB = (props) => {
  const { nodes, materials } = useGLTF("/public/MongoDB.glb");

  const groupRef = useRef();

  useEffect(() => {
    if (!groupRef.current) return;

    groupRef.current.rotation.set(0, -Math.PI / 2.7, 0);
    // Animate the rotation on the Y axis infinitely
    gsap.to(groupRef.current.rotation, {
      y: "-=6.283", // 2 * Math.PI radians = full rotation
      duration: 9,
      repeat: -1,
      ease: "linear",
    });
  }, []);

  return (
    <group position={[-45, 0, -22]}>
    <Center>
    <group
      {...props}
      dispose={null}
      ref={(el) => {
        groupRef.current = el;
      }}
    >
      <group
        
        scale={1}
      >
        <mesh
          geometry={nodes.back.geometry}
          material={materials["back.003"]}
          position={[-0.051, 0.308, 0.118]}
          rotation={[1.534, -0.009, -1.551]}
        />
        <mesh
          geometry={nodes.LOGO.geometry}
          material={materials["logo.004"]}
          position={[0.666, 0.29, 0.275]}
          rotation={[1.534, -0.009, -1.551]}
        />
        <mesh
          geometry={nodes.LOGO_1.geometry}
          material={materials["logo_1.002"]}
          position={[0.531, -0.373, -1.327]}
          rotation={[1.534, -0.009, -1.551]}
        />
      </group>
    </group>
    </Center>
    </group>
  );
};

export default MongoDB;

useGLTF.preload("/public/MongoDB.glb");
