/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 node.glb --draco 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, Center } from "@react-three/drei";
import gsap from "gsap";

const Node = (props) => {
  const { nodes, materials } = useGLTF("/public/node.glb");

  const groupRef = useRef();

  useEffect(() => {
    if (!groupRef.current) return;

    groupRef.current.rotation.set(Math.PI / 2, 0, Math.PI * 2);
    // Animate the rotation on the Y axis infinitely
    gsap.to(groupRef.current.rotation, {
      z: "+=6.283", // 2 * Math.PI radians = full rotation
      duration: 9,
      repeat: -1,
      ease: "linear",
    });
  }, []);

  return (
    <group position={[24, 0, -22]}>
      <Center>
        <group
          {...props}
          dispose={null}
          ref={(el) => {
            groupRef.current = el;
          }}
        >
          <group scale={1}>
            <mesh geometry={nodes.back.geometry} material={materials.back} />
            <mesh
              geometry={nodes.LOGO.geometry}
              material={materials.logo}
              position={[-0.003, 0.469, 0.009]}
            />
          </group>
        </group>
      </Center>
    </group>
  );
};

export default Node;

useGLTF.preload("/public/node.glb");
